host:
  public: 0.0.0.0
  private: 192.168.1.158
  local: 127.0.0.1

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${host.private}:3306/social_api?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true